### ISSUE TITLE
Set up for Gradle plugin

### ISSUE THREAD

**Issue by mfvanek** [mthmulders/pit-stryker-dashboard-reporter#12]
Hi Maarten,
Do you have any plans to create a gradle plugin for Stryker Mutator Dashboard as well?

**Comment by mthmulders** [comment]
Hi Ivan, this is a plugin for PIT, not for Maven. I think it should work equally well if you invoke PIT from Gradle. It's just that I'm completely unfamiliar with Gradle and/or integrating PIT with Gradle.

If you have a working PIT + Gradle project... Maybe you can try this plugin? And please let me know how to enable PIT plugins from Gradle so I can update the project documentation.

**Comment by mfvanek** [comment]
@mthmulders 
Thank you very much for the explanation. I couldn't catch it at first glance.
I've made a try here https://github.com/mfvanek/pg-index-health-demo/pull/27

1) Locally on my Mac it doesn't work due to unknown environment.
**Is it possible to run pitest locally with your reporter?**
```
9:56:28 PM PIT >> SEVERE : Could not reliably determine your environment, this reporter will not work correctly.
9:56:28 PM PIT >> SEVERE : Consider reporting an issue at https://github.com/mthmulders/pit-stryker-dashboard-reporter/issues/new.
9:56:42 PM PIT >> INFO : Uploading report to https://dashboard.stryker-mutator.io/api/reports/--unknown--/--unknown--
9:56:43 PM PIT >> SEVERE : Failed to upload report, please check your dashboard registration!
```
Also it looks like output report hasn't been generated at all (directory build/reports/pitest is empty).

2) On GitHub I've got an error
```
7:11:36 PM PIT >> INFO : Uploading report to https://dashboard.stryker-mutator.io/api/reports/github.com/mfvanek/pg-index-health-demo/27/merge
Error: Exception in thread "main" java.lang.NullPointerException: value
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.checkNameAndValue(HttpRequestBuilderImpl.java:105)
	at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.header(HttpRequestBuilderImpl.java:126)
	at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.header(HttpRequestBuilderImpl.java:43)
	at it.mulders.stryker.pitreporter.dashboard.client.StrykerDashboardClient.uploadReport(StrykerDashboardClient.java:52)
	at it.mulders.stryker.pitreporter.StrykerDashboardMutationResultListener.runEnd(StrykerDashboardMutationResultListener.java:105)
	at org.pitest.mutationtest.config.CompoundTestListener.runEnd(CompoundTestListener.java:46)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.pitest.mutationtest.execute.MutationAnalysisExecutor.signalRunEndToAllListeners(MutationAnalysisExecutor.java:78)
	at org.pitest.mutationtest.execute.MutationAnalysisExecutor.run(MutationAnalysisExecutor.java:57)
	at org.pitest.mutationtest.tooling.MutationCoverage.runAnalysis(MutationCoverage.java:179)
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:138)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:129)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:57)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:98)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
```

**Comment by mthmulders** [comment]
Thanks, Ivan, that looks promising, already!

> 1. Locally on my Mac it doesn't work due to unknown environment.
> **Is it possible to run pitest locally with your reporter?**

This is more or less expected - the reporter tries to figure out repo name, branch name, etc. from the GitHub actions environment, but that is not present on your machine.

You _could_ fake it, e.g. run this:
```bash
STRYKER_DASHBOARD_API_KEY=example \
  GITHUB_REPOSITORY=mfvanek/pg-index-health-demo \
  GITHUB_REF_NAME=feature/trying-pit-dashboard-reporter \
  <your regular Gradle invocation>
```

But note, it will still fail as long as you do not provide the actual value of `STRYKER_DASHBOARD_API_KEY`.

> 2.  On GitHub I've got an error
> ```
> 7:11:36 PM PIT >> INFO : Uploading report to https://dashboard.stryker-mutator.io/api/reports/github.com/mfvanek/pg-index-health-demo/27/merge
> Error: Exception in thread "main" java.lang.NullPointerException: value
> ```

This usually means the Stryker PIT reporter can't find the Stryker Dashboard key.

Did you run Step 1 from the [Setup Guide](https://github.com/mthmulders/pit-stryker-dashboard-reporter#setup): to configure a GitHub actions environment variable named `STRYKER_DASHBOARD_API_KEY`?

Again, if you've got it working, I'd love to learn how you did that, so I can update the documentation for this PIT reporter.

**Comment by hugo-vrijswijk** [comment]
Setting up Gradle should be very similar to pitest-mutation-testing-elements which also has a [guide for Gradle](https://github.com/Wmaarts/pitest-mutation-testing-elements-plugin#gradle)

**Comment by mfvanek** [comment]
Maarten, thanks!
I managed to set up `pit-stryker-dashboard-reporter` in gradle environment.
Key points ([based on](https://gradle-pitest-plugin.solidsoft.info/)):
1) `build.gradle` config
```
plugins {
    ...
    id 'info.solidsoft.pitest' version '1.9.0' // adding pitest gradle plugin
}

// adding dependency
dependencies {
    ...
    pitest 'it.mulders.stryker:pit-dashboard-reporter:0.1.2'
}

// configuring pitest task
pitest {
    junit5PluginVersion = '1.0.0'
    pitestVersion = '1.9.4'
    threads = 4
    // disabling stryker-dashboard for local runs
    outputFormats = System.getenv('STRYKER_DASHBOARD_API_KEY') != null ? ['stryker-dashboard'] : ['HTML']
    timestampedReports = false
    mutationThreshold = 100
}

build.dependsOn 'pitest'

// this is my own set up - running pitest task only after unit tests
tasks.named('pitest').configure {
    mustRunAfter test
}
```

2) And of course `STRYKER_DASHBOARD_API_KEY` in CI yaml-manifest:
```
            -   name: Build
                env:
                    STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
                run: ./gradlew build
```

**Comment by mthmulders** [comment]
Thank you for sharing your findings, @mfvanek. I've [updated README.md](https://github.com/mthmulders/pit-stryker-dashboard-reporter/commit/179c14e065f242b7661821a28e8fe55fcfb89e2b).
