### ISSUE TITLE
Upload fails for branches beginning with a hash sign

### ISSUE THREAD

**Issue by jesperolsson-se** [mthmulders/pit-stryker-dashboard-reporter#66]
When the reporter runs on a branch whose name begins with a `#` (i.e., uses [autolinking](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls)), it will receive a `404 NOT_FOUND`. The branch name is likely dropped en route, since it doesn't appear in the response.

```
{
    "name": "NOT_FOUND",
    "message": "Report \"/github.com/jesperolsson-se/capsyl/\" does not exist",
    "status": 404,
    "errors": [],
    "stack": "NOT_FOUND: Report \"/github.com/jesperolsson-se/capsyl/\" does not exist\n    at ReportsController.parseSlug (file:///app/node_modules/@stryker-mutator/dashboard-backend/dist/src/api/ReportsController.js:84:23)\n    at ReportsController.get (file:///app/node_modules/@stryker-mutator/dashboard-backend/dist/src/api/ReportsController.js:65:43)\n    at file:///app/node_modules/@tsed/platform-params/lib/esm/builder/PlatformParams.js:55:46"
}
```

**Comment by mthmulders** [comment]
Thanks for the report, @jesperolsson-se. I'm checking with the people behind the Stryker Dashboard to see what their API expects.

**Comment by jesperolsson-se** [comment]
Attempted this scenario with `0.1.5` and everything worked as expected.

**Comment by mthmulders** [comment]
Thanks for confirming, @jesperolsson-se. Could you please double-check if this also fixes your other issue, #68?

**Comment by jesperolsson-se** [comment]
@mthmulders 
That was my plan. I simply didn't have time to, yesterday :slightly_smiling_face:

**Comment by mthmulders** [comment]
Happens to all of us, every now and then. Thanks nevertheless!
