### ISSUE TITLE
Upload fails for main branch

### ISSUE THREAD

**Issue by jesperolsson-se** [mthmulders/pit-stryker-dashboard-reporter#68]
When the reporter runs on main it will receive a `404 NOT_FOUND` (and not fail the Github Action).

```
{
    "name": "NOT_FOUND",
    "message": "Version \"main\" does not exist for \"github.com/jesperolsson-se/capsyl\".",
    "status": 404,
    "errors": [],
    "stack": "NOT_FOUND: Version \"main\" does not exist for \"github.com/jesperolsson-se/capsyl\".\n    at ReportsController.get (file:///app/node_modules/@stryker-mutator/dashboard-backend/dist/src/api/ReportsController.js:75:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
}
```

When I try to upload the report manually, it succeeds.
```
STRYKER_DASHBOARD_API_KEY=<secret> GITHUB_REPOSITORY=jesperolsson-se/capsyl GITHUB_REF_NAME=main GITHUB_ACTIONS=true mvn clean verify
```

The behaviour can also be observed in your/this repo (e.g., [here](https://github.com/mthmulders/pit-stryker-dashboard-reporter/actions/runs/3846542535/jobs/6551969435#step:5:673) and [here](https://github.com/mthmulders/pit-stryker-dashboard-reporter/actions/runs/3846543558/jobs/6551971888#step:5:673))

**Comment by mthmulders** [comment]
Interesting - it should fail silently when there's no API key, but when there is one, it shouldn't fail in silence. Rather, it should make a lot of noise about it.

Thanks for brining this up, @jesperolsson-se!

**Comment by mthmulders** [comment]
@jesperolsson-se, [version 0.1.5](https://github.com/mthmulders/pit-stryker-dashboard-reporter/releases/tag/v0.1.5) is now syncing to Maven Central and should arrive shortly. It features improved error handling, and additional troubleshooting capabilities.

Could you try again with this release and let me know how it works for you?

**Comment by jesperolsson-se** [comment]
@mthmulders 
Yes, the new version seems to have resolved everything. Thanks for the quick response!

**Comment by mthmulders** [comment]
Awesome, thanks for confirming!
